app/src/modules/upload/models.py
from src.database import PkModel, Column, db


class FileModel(PkModel):
    __tablename__ = 'files'

    pdf_filename = Column(db.String, nullable=False)
    pdf_filename_alt = Column(db.String, nullable=False)
    keywords = Column(db.Text, nullable=False)
    collocations = Column(db.Text, nullable=False)
    upload_date = Column(db.Date, nullable=False)
    # summarized_text = Column(db.Text, nullable=False)

app/src/modules/upload/forms.py
from flask_wtf import FlaskForm

from flask_wtf.file import FileField, FileAllowed, FileRequired

from src.settings import Config

ALLOWED_EXTENSIONS = Config.get_allowed_file_extensions()


class FileForm(FlaskForm):
    pdf_file = FileField(validators=[FileRequired(), FileAllowed(ALLOWED_EXTENSIONS, 'PDF files only.')])

app/src/app.py
from flask import Flask, render_template

from src.database import db
from src.settings import Config
from src.extensions import extensions, extensions_with_db


def import_models() -> None:
    """Import models here for Flask-Migrate to work."""
    from src.modules.upload.models import FileModel


def register_extensions(app: Flask) -> None:
    """Register Flask extensions."""
    for extension in extensions:
        extension.init_app(app=app)

    for extension in extensions_with_db:
        extension.init_app(app=app, db=db)


def register_blueprints(app: Flask) -> None:
    """
    Method to register list of blueprints to the app.

    :param app: Flask application
    :return: None
    """
    # To check if app contains blueprints we need to be inside the app context
    from .utils import blueprints

    if not blueprints and app.get("CHECK_FOR_BLUEPRINTS") is True:
        message = "The list of blueprints is empty. App won't have any blueprints."
        app.logger.warning(message)
    else:
        for blueprint in blueprints:
            app.register_blueprint(blueprint)


def register_error_handlers(app: Flask) -> None:
    """Register error handlers here."""
    pass


def register_shell_context(app: Flask) -> None:
    """Register shell context here."""
    pass


def register_commands(app: Flask) -> None:
    """Register flask commands here."""
    pass


def configure_logger() -> None:
    """Configure logger here."""
    pass


def create_app() -> Flask:
    """
    Create application factory.

    :return: Flask application
    """
    configure_logger()

    app = Flask(__name__)
    app.config.from_object(Config)

    register_extensions(app)
    register_blueprints(app)
    register_error_handlers(app)
    register_shell_context(app)
    register_commands(app)
    import_models()

    return app

app/src/modules/main/views.py
from flask import Blueprint, render_template, request, send_from_directory

from src.settings import Config
from src.modules.upload.models import FileModel
from src.modules.main.services import filter_files

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='templates/main'
)


@main_blueprint.route('/', methods=['GET', 'POST'])
def index():
    """Main route endpoint."""
    files = FileModel.query.order_by(FileModel.upload_date.desc()).all()

    if request.method == "POST":
        search_query = request.form['query']
        files = filter_files(search_query)

        return render_template('index.html', files=files, search_query=search_query)

    return render_template('index.html', files=files)


@main_blueprint.route('/uploads/<path:filename>', methods=['GET'])
def download(filename):
    full_path = Config.get_upload_path()
    return send_from_directory(full_path, filename)

app/src/modules/upload/views.py
from flask import Blueprint, render_template, flash, redirect, url_for

from src.modules.upload.services import process_uploaded_file
from src.modules.upload.forms import FileForm

upload_blueprint = Blueprint(
    'upload',
    __name__,
    template_folder='templates/upload'
)


@upload_blueprint.route('/upload', methods=['GET', 'POST'])
def upload():
    """Upload route endpoint."""
    form = FileForm()

    if form.validate_on_submit():
        process_uploaded_file(form.pdf_file.data, form.pdf_file.data.filename)

        flash('File processed successfully', 'success')
        return redirect(url_for('main.index'))

    return render_template('upload.html', form=form)

app/src/modules/main/templates/main/index.html
{% extends 'base.html' %}

{% block title %}File Server | NTRS NLP{% endblock %}

{% block content %}
    <h1>NTRS NLP</h1>
    <section class="search">
        <form action="/" method="POST" class="search_form" id="search_form">
            <input type="text" name="query" id="search_input" placeholder="Search by keywords or collocations ..." required>
            <button class="search_butt" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
    </section>

    {% include('nav.html') %}

    {% if search_query %}
        <section class="search">
            <h3>Search Results For: {{ search_query }}</h3>
        </section>
    {% endif %}

    <section class="uploaded_files">
        {% for file in files %}
            <div class="file_card">
                <header class="file_card_header">
                    <div class="pdf_icon">
                        PDF
                    </div>
                    <div class="file_info">
                        <h4>{{ file.pdf_filename }}</h4>
                        <span class="badge date-badge">{{ file.upload_date.strftime('%Y-%m-%d') }}</span>
                    </div>
                    <a class="download_butt" href="{{ url_for('main.download', filename=file.pdf_filename_alt) }}">
                        <i class="fa-regular fa-eye"></i>
                    </a>
                </header>
                <div class="file_card_body">
                    <p>
                        <h5>Keywords:</h5>
                        {{ file.keywords }}
                    </p>
                    <p>
                        <h5>Collocations:</h5>
                        {{ file.collocations }}
                    </p>
                </div>
            </div>
        {% else %}
            <div class="nothing_found">
                <lord-icon
                    src="https://cdn.lordicon.com/cvpqeffe.json"
                    trigger="loop"
                    colors="primary:#112d4e,secondary:#3f72af"
                    stroke="65"
                    style="width:200px;height:200px">
                </lord-icon>
                <h5>Nothing Found</h5>
            </div>
        {% endfor %}
    </section>

    <script type="text/javascript" src="{{ static_url_for('static', filename='js/index.js') }}"></script>
{% endblock %}

app/src/modules/upload/templates/upload/upload.html
{% extends 'base.html' %}

{% block title %}Upload File | NTRS NLP{% endblock %}

{% block content %}
    <h1>Upload File</h1>
    {% include('nav.html') %}
    <form method="POST" enctype="multipart/form-data" id="UploadFile">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            <label for="floatingInput">PDF file to analyze</label>
            {{ form.pdf_file(class_="form-control", id="floatingInput", accept="application/pdf") }}
        </div>
        <button type="submit" class="upload_butt" form="UploadFile">Upload</button>
    </form>
{% endblock %}

app/src/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" href=""/>

    <title>
        {% block title %}
        {% endblock %}
    </title>

    <!--  Fonts  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700&display=swap" rel="stylesheet">

    <!--  Bootstrap  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!--  CSS  -->
    <link rel="stylesheet" href="{{ static_url_for('static', filename='css/styles.css') }}">

    <!--  Icons  -->
    <script src="https://kit.fontawesome.com/07848b287b.js" crossorigin="anonymous"></script>
    <script src="https://cdn.lordicon.com/pzdvqjsp.js"></script>

</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <div class="toast-container p-3">
        {% if get_flashed_messages(with_categories=True) %}
            {% for category, message in get_flashed_messages(with_categories=True) %}
                <div class="toast align-items-center text-bg-{{ category }} border-0" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="d-flex">
                        <div class="toast-body">
                          {{ message }}
                        </div>
                        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <!--  JS  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ static_url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

app/src/templates/nav.html
<nav class="navbar">
    <a href="{{ url_for('main.index') }}">
        <div class="nav_link {% if request.endpoint == 'main.index' %}nav_link__active{% endif %}">
            <div class="nav_link_icon">
                <lord-icon
                    src="https://cdn.lordicon.com/wrprwmwt.json"
                    trigger="morph"
                    colors="primary:#112d4e,secondary:#3f72af"
                    stroke="65"
                    style="width:45px;height:45px">
                </lord-icon>
            </div>
            <div class="nav_link_title">
                Report Server
            </div>
        </div>
    </a>
    <a href="{{ url_for('upload.upload') }}">
        <div class="nav_link {% if request.endpoint == 'upload.upload' %}nav_link__active{% endif %}">
            <div class="nav_link_icon">
                <lord-icon
                    src="https://cdn.lordicon.com/nocovwne.json"
                    trigger="hover"
                    colors="primary:#112d4e,secondary:#3f72af"
                    stroke="65"
                    style="width:45px;height:45px">
                </lord-icon>
            </div>
            <div class="nav_link_title">
                Upload File
            </div>
        </div>
    </a>
</nav>